#!/usr/bin/env python3
"""Build every catalogue view from the hand-curated source of truth.

Inputs
  catalog/resources.jsonl             hand-curated rows (schema v2); the only file humans edit
  catalog/taxonomy.json               domains, sections and kinds with zh + en titles and notes
  catalog/observed.jsonl              machine observations written by scripts/check-links.py
                                      (append-only; the latest record per id wins)
  docs/assets/thumbs/manifest.json    thumbnail manifest written by scripts/shoot-catalog.mjs (optional)

Outputs (generated; never edit by hand)
  skills/design-studio/references/catalog/catalog.jsonl   compact projection read by scripts/catalog.py
  skills/design-studio/references/catalog/taxonomy.json   domains and sections with counts, for catalog.py
  skills/design-studio/references/catalog/<domain>.md     one readable table view per domain
  skills/design-studio/references/catalog/README.md       how to query, column legend, domain list
  docs/data/catalog.json, docs/data/catalog.js            site data (catalog.js sets window.CATALOG_V2)
  docs/data/thumbs.js                                     window.THUMBS: ids with a QA-passed thumbnail
  docs/data/lab-catalog.js                                legacy window.CATALOG + window.CATALOG_ZH for docs/lab/
  docs/data/llms.txt                                      plain-text catalogue for agents
  docs/index.html, docs/catalog/index.html                the <!-- gen:* --> regions only (scripts/site_pages.py)

Usage
  scripts/build-catalog.py            validate, then write every output
  scripts/build-catalog.py --check    exit 1 if the catalogue is invalid or any generated file is stale
"""
import collections
import json
import pathlib
import re
import shutil
import sys

from site_pages import site_pages

ROOT = pathlib.Path(__file__).resolve().parent.parent
RESOURCES = ROOT / 'catalog' / 'resources.jsonl'
TAXONOMY = ROOT / 'catalog' / 'taxonomy.json'
OBSERVED = ROOT / 'catalog' / 'observed.jsonl'
THUMB_DIR = ROOT / 'docs' / 'assets' / 'thumbs'
MANIFEST = THUMB_DIR / 'manifest.json'
SKILL_OUT = ROOT / 'skills' / 'design-studio' / 'references' / 'catalog'
DOCS_OUT = ROOT / 'docs' / 'data'
# Generated by the v1 build; the v2 build owns their removal.
LEGACY = [ROOT / 'skills' / 'design-studio' / 'references' / 'resources',
          ROOT / 'skills' / 'design-studio' / 'references' / 'resource-map.md']

FIELDS = ['id', 'name', 'name_zh', 'url', 'domain', 'section', 'also', 'kind', 'tags', 'best_for', 'how_to_use',
          'zh', 'zh_how', 'access', 'login', 'license', 'tier', 'status', 'lang', 'region', 'entry_points', 'api',
          'caveats', 'origin', 'added']
REQUIRED = ['id', 'name', 'url', 'domain', 'section', 'kind', 'tags', 'best_for', 'how_to_use', 'zh', 'access',
            'login', 'tier', 'status', 'lang', 'region', 'origin', 'added']
ENUMS = {'access': ('free', 'freemium', 'paid'),
         'tier': ('S', 'A', 'B'),
         'status': ('active', 'slow', 'archived', 'sunset'),
         'lang': ('en', 'zh', 'ja', 'ko', 'multi'),
         'region': ('global', 'cn', 'jp', 'kr')}
REACH = ('static', 'js', 'unknown', 'blocked')          # also the sort order: what a plain fetch can use first
TIER_RANK = {'S': 0, 'A': 1, 'B': 2}
S_QUOTA = 0.15
PROJECTION = ['id', 'name', 'name_zh', 'url', 'domain', 'section', 'also', 'kind', 'tags', 'best_for',
              'how_to_use', 'zh', 'access', 'login', 'license', 'tier', 'status', 'region', 'agent_access',
              'entry_points', 'api', 'caveats']
SITE_FIELDS = ['id', 'name', 'name_zh', 'url', 'host', 'domain', 'section', 'also', 'kind', 'tags', 'best_for',
               'how_to_use', 'zh', 'zh_how', 'access', 'login', 'license', 'tier', 'status', 'lang', 'region',
               'entry_points', 'api', 'caveats', 'agent_access', 'thumb', 'added', 'checked_at']
SCRIPT_DIR = 'skills/design-studio/scripts'                  # where catalog.py lives, for the commands in the views
NOTICE = 'Generated by scripts/build-catalog.py from catalog/resources.jsonl. Do not edit by hand.'


# ---- load ---------------------------------------------------------------------------------------

def read_jsonl(path):
    if not path.exists():
        return []
    return [json.loads(line) for line in path.read_text().splitlines() if line.strip()]


def load():
    rows = read_jsonl(RESOURCES)
    taxonomy = json.loads(TAXONOMY.read_text())
    observed = read_jsonl(OBSERVED)
    manifest = json.loads(MANIFEST.read_text()) if MANIFEST.exists() else {'items': {}}
    return rows, taxonomy, observed, manifest


def latest_observations(observed):
    latest = {}
    for record in observed:                                   # later lines win ties
        seen = latest.get(record.get('id'))
        if seen is None or record.get('checked_at', '') >= seen.get('checked_at', ''):
            latest[record.get('id')] = record
    return latest


def qa_passed_thumbs(manifest, ids):
    thumbs = {}
    for rid, item in manifest.get('items', {}).items():
        ok = (rid in ids and item.get('file') and item.get('source') in ('screenshot', 'og', 'github')
              and (item.get('qa') or {}).get('verdict') == 'ok' and (THUMB_DIR / item['file']).exists())
        if ok:
            thumbs[rid] = {'src': f"assets/thumbs/{item['file']}", 'source': item['source'],
                           'captured_at': item.get('captured_at')}
    return thumbs


# ---- validate -----------------------------------------------------------------------------------

def norm_url(url):
    return re.sub(r'^https?://(www\.)?', '', url).rstrip('/').lower()


def is_url(value):
    return isinstance(value, str) and re.match(r'https?://\S+$', value) is not None


def validate_taxonomy(taxonomy):
    errors = []
    domains = [d.get('id') for d in taxonomy.get('domains', [])]
    if len(domains) != len(set(domains)):
        errors.append('taxonomy.json: duplicate domain id')
    for d in taxonomy.get('domains', []):
        for key in ('id', 'zh', 'en', 'blurb_zh', 'blurb_en', 'hue', 'sections'):
            if key not in d:
                errors.append(f"taxonomy.json: domain {d.get('id')!r} missing {key}")
        sections = [s.get('id') for s in d.get('sections', [])]
        if len(sections) != len(set(sections)):
            errors.append(f"taxonomy.json: duplicate section id in {d.get('id')}")
        for s in d.get('sections', []):
            for key in ('id', 'zh', 'en', 'note_zh', 'note_en'):
                if not s.get(key):
                    errors.append(f"taxonomy.json: section {d.get('id')}:{s.get('id')} missing {key}")
    kinds = [k.get('id') for k in taxonomy.get('kinds', [])]
    if not kinds or len(kinds) != len(set(kinds)):
        errors.append('taxonomy.json: kinds missing or duplicated')
    for k in taxonomy.get('kinds', []):
        for key in ('id', 'zh', 'en', 'note_zh', 'note_en'):
            if not k.get(key):
                errors.append(f"taxonomy.json: kind {k.get('id')!r} missing {key}")
    return errors


def validate_row(row, homes, kinds):
    errors, warnings = [], []
    where = row.get('id', '?')
    for key in row:
        if key not in FIELDS:
            hint = ' (moved to catalog/observed.jsonl)' if key == 'agent_access' else \
                   ' (replaced by status)' if key == 'updated' else ''
            errors.append(f'{where}: unknown field {key}{hint}')
    for key in REQUIRED:
        if key not in row or row[key] in ('', None, []):
            errors.append(f'{where}: missing {key}')
    for key, allowed in ENUMS.items():
        if key in row and row[key] not in allowed:
            errors.append(f'{where}: {key}={row[key]!r} not in {list(allowed)}')
    if not re.fullmatch(r'[a-z0-9][a-z0-9-]*', row.get('id', '')):
        errors.append(f'{where}: id must be kebab-case')
    if row.get('kind') not in kinds:
        errors.append(f"{where}: unknown kind {row.get('kind')!r}")
    home = f"{row.get('domain')}:{row.get('section')}"
    if home not in homes:
        errors.append(f'{where}: unknown domain/section {home}')
    also = row.get('also', [])
    if not isinstance(also, list) or len(also) != len(set(also)) or home in also \
            or any(a not in homes for a in also):
        errors.append(f'{where}: also must list distinct known "domain:section" homes other than {home}')
    tags = row.get('tags')
    if not isinstance(tags, list) or not 1 <= len(tags) <= 6 or not all(isinstance(t, str) and t for t in tags):
        errors.append(f'{where}: tags must be 1-6 strings')
    if not isinstance(row.get('login'), bool):
        errors.append(f'{where}: login must be true or false')
    if not is_url(row.get('url')):
        errors.append(f"{where}: url {row.get('url')!r} is not an http(s) URL")
    elif not row['url'].startswith('https://'):
        warnings.append(f'{where}: url is not https')
    for ep in row.get('entry_points', []):
        if not isinstance(ep, dict) or not ep.get('label') or not is_url(ep.get('url')):
            errors.append(f'{where}: entry_points items need a label and an http(s) url')
    if 'api' in row:
        api = row['api']
        if not isinstance(api, dict) or not api.get('url') or not is_url(api.get('sample')) or '{' in api['sample']:
            errors.append(f'{where}: api needs a url template and a concrete http(s) sample')
    if not isinstance(row.get('caveats', []), list):
        errors.append(f'{where}: caveats must be a list')
    if not re.fullmatch(r'\d{4}-\d{2}-\d{2}', str(row.get('added', ''))):
        errors.append(f'{where}: added must be YYYY-MM-DD')
    return errors, warnings


def validate(rows, taxonomy, latest):
    errors = validate_taxonomy(taxonomy)
    warnings = []
    homes = {f"{d['id']}:{s['id']}" for d in taxonomy['domains'] for s in d['sections']}
    kinds = {k['id'] for k in taxonomy['kinds']}
    ids, urls = set(), {}
    for row in rows:
        e, w = validate_row(row, homes, kinds)
        errors += e
        warnings += w
        rid = row.get('id')
        if rid in ids:
            errors.append(f'{rid}: duplicate id')
        ids.add(rid)
        key = norm_url(row.get('url', ''))
        if key in urls:
            errors.append(f'{rid}: duplicate url (also {urls[key]})')
        urls[key] = rid
    for rid, record in latest.items():
        if record.get('agent_access') not in REACH:
            errors.append(f"observed.jsonl: {rid}: agent_access={record.get('agent_access')!r} not in {list(REACH)}")
        if rid not in ids:
            warnings.append(f'observed.jsonl: {rid} is not in resources.jsonl')
    by_domain = collections.defaultdict(list)
    for row in rows:
        by_domain[row.get('domain')].append(row)
    for domain, members in by_domain.items():
        s_count = sum(r.get('tier') == 'S' for r in members)
        if s_count > S_QUOTA * len(members):
            errors.append(f'{domain}: {s_count}/{len(members)} rows are S (quota {S_QUOTA:.0%})')
    for row in rows:
        reach = latest.get(row.get('id'), {}).get('agent_access', 'unknown')
        if row.get('tier') == 'S' and reach != 'static' and not row.get('entry_points') and not row.get('api'):
            warnings.append(f"{row.get('id')}: S row has no agent path (reach {reach}, no entry_points or api)")
    return errors, warnings


# ---- shared helpers -------------------------------------------------------------------------------

def host(url):
    return re.sub(r'^https?://(www\.)?', '', url).split('/')[0].split('?')[0].lower()


def data_date(rows, latest, manifest):
    """The 'generated' date: the newest date found in the inputs, so the output is reproducible."""
    dates = [r['added'] for r in rows] + [o.get('checked_at', '')[:10] for o in latest.values()]
    dates.append(str(manifest.get('generated', ''))[:10])
    return max(d for d in dates if d)


def domain_list(taxonomy, rows):
    counts = collections.Counter((r['domain'], r['section']) for r in rows)
    out = []
    for d in taxonomy['domains']:
        sections = [dict(s, count=counts[(d['id'], s['id'])]) for s in d['sections']]
        out.append({**{k: d[k] for k in ('id', 'zh', 'en', 'blurb_zh', 'blurb_en', 'hue')},
                    'count': sum(s['count'] for s in sections), 'sections': sections})
    return out


def working_order(rows, reach_of):
    """Tier first, then what a plain fetch can use, then authored order."""
    position = {r['id']: n for n, r in enumerate(rows)}
    return sorted(rows, key=lambda r: (TIER_RANK[r['tier']], REACH.index(reach_of(r)), position[r['id']]))


def js_file(assignments):
    body = ''.join(f'window.{name} = {json.dumps(value, ensure_ascii=False, separators=(",", ":"))};\n'
                   for name, value in assignments)
    return f'// {NOTICE}\n{body}'


# ---- skill views --------------------------------------------------------------------------------

def cell(text):
    return str(text).replace('\n', ' ').replace('|', '\\|').strip()


def access_cell(row):
    parts = [row['access']]
    if row['login']:
        parts.append('login')
    if row.get('license'):
        parts.append(row['license'])
    if row['status'] != 'active':
        parts.append(row['status'])
    return ' · '.join(parts)


def entry_cell(row):
    parts = [f"[{ep['label']}]({ep['url']})" for ep in row.get('entry_points', [])]
    if row.get('api'):
        parts.append(f"API `{row['api']['url']}`")
    return '; '.join(parts)


def render_domain(d, rows, reach_of):
    crossed = sum(any(a.startswith(d['id'] + ':') for a in r.get('also', [])) for r in rows if r['domain'] != d['id'])
    out = [f'<!-- {NOTICE} -->', f"# {d['en']} · {d['zh']}", '', d['blurb_en'], '',
           f"{d['count']} resources" + (f', plus {crossed} cross-listed from other domains' if crossed else '') +
           f'. Columns are explained in README.md; `python3 "$S/catalog.py" find` (`S` = `{SCRIPT_DIR}`) '
           'searches every domain at once. '
           'Rows are sorted by tier, then by reach, so what an agent can fetch comes first.', '']
    for s in d['sections']:
        home = f"{d['id']}:{s['id']}"
        members = [r for r in rows if f"{r['domain']}:{r['section']}" == home or home in r.get('also', [])]
        if not members:
            continue
        out += [f"## {s['en']} · {s['zh']}", '', s['note_en'], '',
                '| Resource | Best for | How to use | Tier | Kind | Reach | Access · licence | Entry point |',
                '| --- | --- | --- | --- | --- | --- | --- | --- |']
        for r in working_order(members, reach_of):
            name = r['name'] + (f" ({r['lang']})" if r['lang'] != 'en' else '')
            if r['domain'] != d['id'] or r['section'] != s['id']:
                name += f" (home: {r['domain']})" if r['domain'] != d['id'] else f" (home: {r['section']})"
            out.append(f"| [{cell(name)}]({r['url']}) | {cell(r['best_for'])} | {cell(r['how_to_use'])} | "
                       f"{r['tier']} | {r['kind']} | {reach_of(r)} | {cell(access_cell(r))} | {cell(entry_cell(r))} |")
        out.append('')
    return '\n'.join(out)


def render_readme(domains, rows, kinds, generated):
    tiers = collections.Counter(r['tier'] for r in rows)
    lines = [
        f'<!-- {NOTICE} -->',
        '# Design resource catalogue',
        '',
        f'{len(rows)} hand-curated design resources in {len(domains)} domains (S {tiers["S"]}, A {tiers["A"]}, '
        f'B {tiers["B"]}); data as of {generated}. Everything here is generated from the lab repository; '
        'report a dead link or a wrong licence to the maintainer instead of editing these files.',
        '',
        '## Query it (preferred)',
        '',
        f'`S` = `{SCRIPT_DIR}` (the design-studio skill\'s scripts folder; the script finds its data from any '
        'working directory):',
        '',
        '```',
        'python3 "$S/catalog.py" find "font pairing" --limit 8      # weighted keyword search, zh or en',
        'python3 "$S/catalog.py" find 配色 --reach static            # only what a plain fetch can read',
        'python3 "$S/catalog.py" find chart --domain dataviz --tier S --free',
        'python3 "$S/catalog.py" route "dashboard for a factory big screen"   # best sections + top rows',
        'python3 "$S/catalog.py" show mobbin                         # every field of one row',
        'python3 "$S/catalog.py" recipes                             # machine endpoints with samples',
        'python3 "$S/catalog.py" domains                             # domains and sections with counts',
        '```',
        '',
        'Add `--json` to `find` for machine-readable output. Filters: `--domain --section --kind --tier '
        '--region --reach --free --limit`.',
        '',
        '## Without Python: read one domain file',
        '',
        '| Domain | File | Resources | S | Covers |',
        '| --- | --- | --- | --- | --- |',
    ]
    for d in domains:
        s_count = sum(r['tier'] == 'S' for r in rows if r['domain'] == d['id'])
        covers = ', '.join(s['en'] for s in d['sections'])
        lines.append(f"| {d['en']} · {d['zh']} | {d['id']}.md | {d['count']} | {s_count} | {cell(covers)} |")
    lines += [
        '',
        'Each file lists its sections with one table per section. Rows cross-listed from another domain say '
        '`(home: <domain>)`.',
        '',
        '## Columns',
        '',
        '- **Tier**: `S` first place to look, `A` strong, `B` niche or with a stated weakness.',
        '- **Reach** (observed by a plain fetch, not a guess): `static` = a web fetch can read it; `js` = needs '
        'a real browser; `blocked` = bot protection or a login wall, so give the user the link and what to look '
        'for; `unknown` = the last check got no usable answer from the maintainer\'s network (unreachable, moved '
        'or not yet checked), which is not proof that it is down. If a source is unreachable, pick another in the '
        'same section.',
        '- **Access · licence**: cost (`free`, `freemium`, `paid`), `login` when content is gated, the licence '
        'where it matters, and the status when it is not `active` (`slow`, `archived`, `sunset`). Check the '
        'licence before using any asset.',
        '- **Entry point**: validated deep links (mirrors an agent can fetch when the main site is walled) and '
        'machine endpoints. `python3 "$S/catalog.py" recipes` lists every endpoint with a sample request.',
        '- **Region** (catalog.jsonl, `--region`): `cn`, `jp`, `kr` for resources made for that market, '
        'otherwise `global`.',
        '- **Kind** (what the resource is, whatever its domain):',
        *[f"  - `{k['id']}` {k['note_en']}" for k in kinds],
        '',
        'Choose two to four sources of different kinds for any research task, and date what you take from '
        'trend-driven sources.',
        '',
    ]
    return '\n'.join(lines)


def render_llms(domains, rows, reach_of, generated):
    lines = ['# Design Skill Lab: design resource catalogue', '',
             f'> {len(rows)} hand-curated design resources for designers and coding agents, in {len(domains)} '
             'domains. One line per resource: name — url — 中文说明 — best for — [tier · reach]. Tier S is the first '
             'place to look; reach is what a plain web fetch got (static, js, blocked, unknown).',
             f'> Generated from catalog/resources.jsonl, data as of {generated}. '
             'Source: https://github.com/caocong1/design-skill-lab', '']
    for d in domains:
        lines += [f"## {d['en']} · {d['zh']} ({d['id']})", '']
        for s in d['sections']:
            members = [r for r in rows if r['domain'] == d['id'] and r['section'] == s['id']]
            if not members:
                continue
            lines.append(f"### {s['en']} · {s['zh']}")
            lines += [f"- {r['name']} — {r['url']} — {r['zh']} — {r['best_for']} [{r['tier']} · {reach_of(r)}]"
                      for r in working_order(members, reach_of)]
            lines.append('')
    return '\n'.join(lines)


# ---- build --------------------------------------------------------------------------------------

def project(row, keys):
    return {k: row[k] for k in keys if row.get(k) not in (None, '', [], False)}


def site_row(row, reach, thumb, checked_at):
    full = dict(row, host=host(row['url']), agent_access=reach, thumb=thumb, checked_at=checked_at)
    defaults = {'also': [], 'entry_points': [], 'caveats': []}
    return {k: full.get(k, defaults.get(k)) for k in SITE_FIELDS}


def legacy_row(row, reach):
    out = {k: row[k] for k in ('id', 'name', 'url', 'domain', 'section', 'kind', 'tags', 'best_for', 'how_to_use',
                               'access', 'login')}
    out['agent_access'] = reach
    if row.get('license'):
        out['license'] = row['license']
    out['tier'] = row['tier']
    out['updated'] = 'archived' if row['status'] == 'sunset' else row['status']
    for k in ('lang', 'origin', 'added'):
        out[k] = row[k]
    return out


def build(rows, taxonomy, latest, manifest):
    reach_of = lambda r: latest.get(r['id'], {}).get('agent_access', 'unknown')
    thumbs = qa_passed_thumbs(manifest, {r['id'] for r in rows})
    generated = data_date(rows, latest, {})              # skill files do not churn when thumbnails change
    site_generated = data_date(rows, latest, manifest)
    domains = domain_list(taxonomy, rows)
    kinds = taxonomy['kinds']

    files = {}
    files[SKILL_OUT / 'catalog.jsonl'] = ''.join(
        json.dumps(project(dict(r, agent_access=reach_of(r)), PROJECTION), ensure_ascii=False,
                   separators=(',', ':')) + '\n' for r in rows)
    files[SKILL_OUT / 'taxonomy.json'] = json.dumps({'generated': generated, 'domains': domains, 'kinds': kinds},
                                                    ensure_ascii=False, indent=1) + '\n'
    for d in domains:
        files[SKILL_OUT / f"{d['id']}.md"] = render_domain(d, rows, reach_of)
    files[SKILL_OUT / 'README.md'] = render_readme(domains, rows, kinds, generated)

    counted = lambda key: dict(collections.Counter(key(r) for r in rows).most_common())
    counts = {'resources': len(rows), 'domains': len(domains),
              'sections': sum(len(d['sections']) for d in domains),
              'tiers': {t: sum(r['tier'] == t for r in rows) for t in 'SAB'},
              'reach': {a: sum(reach_of(r) == a for r in rows) for a in REACH},
              'kinds': counted(lambda r: r['kind']), 'access': counted(lambda r: r['access']),
              'status': counted(lambda r: r['status']), 'regions': counted(lambda r: r['region']),
              'langs': counted(lambda r: r['lang']), 'thumbs': len(thumbs)}
    site = {'generated': site_generated, 'counts': counts, 'domains': domains, 'kinds': kinds,
            'resources': [site_row(r, reach_of(r), thumbs.get(r['id']), latest.get(r['id'], {}).get('checked_at'))
                          for r in rows]}
    files[DOCS_OUT / 'catalog.json'] = json.dumps(site, ensure_ascii=False, separators=(',', ':')) + '\n'
    files[DOCS_OUT / 'catalog.js'] = js_file([('CATALOG_V2', site)])
    files[DOCS_OUT / 'thumbs.js'] = js_file([('THUMBS', {rid: {'src': t['src'], 'source': t['source']}
                                                         for rid, t in thumbs.items()})])
    lab = {'domains': {d['id']: {'title': d['en'], 'intro': d['blurb_en'], 'zh': d['zh'], 'blurb': d['blurb_zh'],
                                 'hue': d['hue'],
                                 'sections': [{'id': s['id'], 'title': s['en'], 'note': s['note_en'],
                                               'zh': s['zh'], 'note_zh': s['note_zh']} for s in d['sections']]}
                       for d in domains},
           'kinds': {k['id']: k['zh'] for k in kinds},       # labels for kinds the lab's content.js predates
           'resources': [legacy_row(r, reach_of(r)) for r in rows]}
    files[DOCS_OUT / 'lab-catalog.js'] = js_file([('CATALOG', lab), ('CATALOG_ZH', {r['id']: r['zh'] for r in rows})])
    files[DOCS_OUT / 'llms.txt'] = render_llms(domains, rows, reach_of, generated)
    files.update(site_pages(site, ROOT / 'docs'))
    summary = {'generated': site_generated, 'counts': counts}
    return files, summary


def extras(files):
    """Files inside the generated folders that the build did not produce, plus the v1 leftovers."""
    owned = set(files)
    found = [p for out in (SKILL_OUT, DOCS_OUT) if out.exists() for p in sorted(out.rglob('*'))
             if p.is_file() and p not in owned]
    return found + [p for p in LEGACY if p.exists()]


def main():
    rows, taxonomy, observed, manifest = load()
    latest = latest_observations(observed)
    errors, warnings = validate(rows, taxonomy, latest)
    if '--check' not in sys.argv:
        for w in warnings:
            print(f'warning: {w}')
    if errors:
        sys.exit('catalogue invalid:\n  ' + '\n  '.join(errors))
    files, summary = build(rows, taxonomy, latest, manifest)
    rel = lambda p: str(p.relative_to(ROOT))
    if '--check' in sys.argv:
        stale = [rel(p) for p, text in files.items() if not p.exists() or p.read_text() != text]
        stale += [f'{rel(p)} (not generated by this build: remove it)' for p in extras(files)]
        if stale:
            sys.exit('stale generated files (run scripts/build-catalog.py):\n  ' + '\n  '.join(stale))
        print(f"OK  catalogue valid, {summary['counts']['resources']} entries, {len(files)} generated files fresh, "
              f'{len(warnings)} warnings (run without --check to list them)')
        return
    for path, text in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
    for path in extras(files):
        shutil.rmtree(path) if path.is_dir() else path.unlink()
        print(f'removed {rel(path)}')
    c = summary['counts']
    print(f"{c['resources']} entries in {c['domains']} domains / {c['sections']} sections, data as of "
          f"{summary['generated']}")
    print(f"  tiers {c['tiers']}  reach {c['reach']}  regions {c['regions']}  thumbs {c['thumbs']}")
    print(f'  {len(files)} files written, {len(warnings)} warnings')


if __name__ == '__main__':
    main()
