#!/usr/bin/env node
// Batch screenshots of catalogued sites for the lab page (docs/assets/shots/).
// Usage:
//   node scripts/shoot-catalog.mjs [--tiers S,A,B] [--ids id1,id2] [--force]
//                                  [--concurrency 6] [--wait 3500] [--timeout 20000]
// Output: docs/assets/shots/<id>.jpg (1200x750, jpeg q60) + manifest.json + .failed.txt
// Dependency: playwright (npx). Re-runnable: existing files are skipped unless --force.
import { chromium } from 'playwright';
import { readFileSync, writeFileSync, existsSync, mkdirSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const OUT = join(ROOT, 'docs/assets/shots');
mkdirSync(OUT, { recursive: true });

const args = process.argv.slice(2);
const opt = (name, dflt) => {
  const i = args.indexOf('--' + name);
  return i > -1 ? args[i + 1] : dflt;
};
const tiers = (opt('tiers', 'S')).split(',');
const onlyIds = opt('ids', '').split(',').filter(Boolean);
const force = args.includes('--force');
const CONC = Number(opt('concurrency', 6));
const WAIT = Number(opt('wait', 3500));
const TIMEOUT = Number(opt('timeout', 20000));

const rows = readFileSync(join(ROOT, 'catalog/resources.jsonl'), 'utf8')
  .split('\n').filter(Boolean).map((l) => JSON.parse(l));

const todo = rows.filter((r) =>
  (onlyIds.length ? onlyIds.includes(r.id) : tiers.includes(r.tier)) &&
  (force || !existsSync(join(OUT, r.id + '.jpg'))));

console.log(`shoot-catalog: ${todo.length} to capture (tiers=${tiers} ids=${onlyIds.length || '—'})`);
const failed = [];
let done = 0;

const browser = await chromium.launch({ channel: 'chrome', headless: true });
async function shoot(r) {
  const file = join(OUT, r.id + '.jpg');
  const ctx = await browser.newContext({
    viewport: { width: 1200, height: 750 },
    deviceScaleFactor: 1,
    ignoreHTTPSErrors: true,
    locale: 'en-US',
  });
  const page = await ctx.newPage();
  try {
    await page.route('**/*', (route) =>
      ['media', 'websocket'].includes(route.request().resourceType())
        ? route.abort() : route.continue());
    // Slow/blocked sites: commit is enough; capture whatever has painted.
    await page.goto(r.url, { waitUntil: 'commit', timeout: TIMEOUT }).catch((e) => {
      if (page.url() === 'about:blank') throw e;
    });
    await page.waitForTimeout(WAIT);
    // Dismiss the most common full-screen cookie/consent overlays by keyboard.
    await page.keyboard.press('Escape').catch(() => {});
    await page.screenshot({ path: file, type: 'jpeg', quality: 60 });
    done++;
    if (done % 10 === 0 || done === todo.length) console.log(`  ${done}/${todo.length}`);
  } catch (e) {
    failed.push(`${r.id}\t${r.url}\t${String(e.message || e).split('\n')[0]}`);
  } finally {
    await ctx.close().catch(() => {});
  }
}

const queue = [...todo];
await Promise.all(Array.from({ length: CONC }, async () => {
  while (queue.length) await shoot(queue.shift());
}));
await browser.close();

const manifest = readdirSync(OUT).filter((f) => f.endsWith('.jpg')).map((f) => f.slice(0, -4)).sort();
writeFileSync(join(OUT, 'manifest.json'), JSON.stringify(manifest, null, 0) + '\n');
// JS form so file:// viewing works (fetch of a local json is blocked there).
writeFileSync(join(OUT, '../shots.js'),
  '/* Generated by scripts/shoot-catalog.mjs - ids with a screenshot at assets/shots/<id>.jpg */\n' +
  'window.SHOTS=' + JSON.stringify(manifest) + ';\n');
writeFileSync(join(OUT, '.failed.txt'), failed.join('\n') + (failed.length ? '\n' : ''));
console.log(`done: ${manifest.length} shots present, ${failed.length} failed this run`);
if (failed.length) console.log('failures written to docs/assets/shots/.failed.txt');
