#!/usr/bin/env python3
"""Query the design resource catalogue that ships with this skill. Python 3 stdlib only; any working directory.

  catalog.py find <keywords...> [--domain D] [--section S] [--kind K] [--tier S,A] [--region cn]
                                [--reach static,js] [--free] [--limit 10] [--json]
  catalog.py show <id>              every field of one resource
  catalog.py route "<question>"     the best domains/sections for a need, with their top resources
  catalog.py recipes [domain]       machine endpoints (APIs, raw-SVG CDNs, mirrors) with a sample request
  catalog.py domains                domains and sections with counts

Keywords may be English or Chinese (Chinese is matched by known words and character pairs).
Ranking: keyword score (name > tags > Chinese text, best_for > section title, how_to_use > host; rarer words
count more; a row matching a word and its synonym, e.g. 配色 in the Chinese text and "palette" in the English,
counts more than one matching either), then tier, then reach (static before js, unknown, blocked), so what a
plain fetch can use comes first. Scores within the same quarter of the best score count as equally relevant
(keyword scores are too coarse to rank closer than that), so tier and reach decide among them.
Data: ../references/catalog/catalog.jsonl and taxonomy.json, generated by the Design Skill Lab.
"""
import argparse
import difflib
import json
import math
import pathlib
import re
import sys

DATA = pathlib.Path(__file__).resolve().parent.parent / 'references' / 'catalog'
TIER_RANK = {'S': 0, 'A': 1, 'B': 2}
REACH = ('static', 'js', 'unknown', 'blocked')
WEIGHTS = {'name': 6, 'tags': 4, 'zh': 3, 'best_for': 3, 'home': 1.5, 'how_to_use': 1.5, 'host': 1}
ZH_WEIGHT_FOR_CHINESE = 4       # a Chinese word can only match the Chinese text, so a hit there says a bit more
SYNONYM_WEIGHT = 0.6
BANDS = 4                       # relevance bands: quarters of the best score
CJK = '぀-ヿ㐀-䶿一-鿿가-힯豈-﫿'
STOP = {'a', 'an', 'and', 'any', 'are', 'as', 'at', 'be', 'best', 'by', 'can', 'do', 'find', 'for', 'from',
        'good', 'how', 'i', 'in', 'into', 'is', 'it', 'me', 'my', 'need', 'of', 'on', 'or', 'some', 'that',
        'the', 'this', 'to', 'use', 'want', 'what', 'where', 'which', 'with'}
STOP_ZH = {'一个', '一些', '我想', '想找', '需要', '怎么', '如何', '什么', '推荐', '哪些', '有没', '没有', '可以',
           '用于', '适合', '找个', '给我', '参考', '资源', '网站', '工具'}
# Bridges between the words people type and the words the catalogue uses. Keys are matched as whole words
# (English) or as substrings of a Chinese run; each alternative scores at SYNONYM_WEIGHT.
SYNONYMS = {
    'color': ['colour'], 'colour': ['color'], 'palette': ['colour'], 'font': ['typeface'],
    'typeface': ['font'], 'typography': ['type', 'typesetting'], 'animation': ['motion'],
    'motion': ['animation'], 'easing': ['bezier', 'spring', 'curve'], 'curve': ['easing', 'bezier'],
    'chart': ['dataviz', 'visualisation'], 'dataviz': ['chart'], 'visualization': ['visualisation', 'dataviz'],
    'dashboard': ['big-screen'], 'accessibility': ['a11y', 'accessible'], 'a11y': ['accessibility'],
    'ai': ['agent', 'llm', 'genai'], 'logo': ['identity', 'brand'],
    'mockup': ['mock-up'], 'deck': ['slides', 'presentation'], 'slides': ['deck', 'presentation'],
    'elderly': ['accessibility', 'inclusive'],
    '配色': ['palette', 'colour'], '颜色': ['colour'], '色彩': ['colour'], '色板': ['palette'],
    '色阶': ['scale', 'palette'], '对比度': ['contrast'], '渐变': ['gradient'],
    '字体': ['font', 'typeface'], '排版': ['typography', 'typesetting'], '字号': ['type-scale', 'fluid-type'],
    '中文': ['cjk', 'chinese'], '图标': ['icon'], '动效': ['motion', 'animation'], '动画': ['animation', 'motion'],
    '曲线': ['easing', 'bezier', 'curve'], '缓动': ['easing'], '弹簧': ['spring'], '转场': ['transition'],
    '大屏': ['big-screen', 'dashboard'], '仪表盘': ['dashboard'], '看板': ['dashboard'], '图表': ['chart'],
    '可视化': ['dataviz', 'visualisation', 'chart'], '无障碍': ['accessibility', 'a11y'],
    '适老化': ['accessibility', 'inclusive', 'elderly'], '读屏': ['screen reader', 'aria'],
    '插画': ['illustration'], '摄影': ['photo'], '照片': ['photo'], '图片': ['photo', 'image'],
    '样机': ['mockup'], '背景': ['background'], '纹理': ['texture', 'grain'],
    '品牌': ['brand', 'identity'], '标志': ['logo'], '商标': ['trademark'], '命名': ['naming'],
    '海报': ['poster'], '包装': ['packaging'], '封面': ['cover'], '演示': ['deck', 'slides'],
    '幻灯片': ['slides', 'deck'], '落地页': ['landing'], '官网': ['landing', 'website'], '定价': ['pricing'],
    '组件': ['component'], '设计系统': ['design system'], '规范': ['guideline', 'guidelines'],
    '小程序': ['mini-program'], '鸿蒙': ['harmonyos'], '苹果': ['apple', 'ios'], '安卓': ['android'],
    '表单': ['form'], '表格': ['table'], '引导': ['onboarding'], '流程': ['flow'], '界面': ['ui', 'screen'],
    '暗色': ['dark'], '深色': ['dark'], '灵感': ['inspiration', 'gallery'], '社区': ['community'], '智能体': ['agent'], '提示词': ['prompt'],
}


def load():
    path = DATA / 'catalog.jsonl'
    if not path.exists():
        sys.exit(f'catalogue not found at {path}; reinstall the design-studio skill')
    rows = [json.loads(line) for line in path.read_text(encoding='utf-8').splitlines() if line.strip()]
    taxonomy = json.loads((DATA / 'taxonomy.json').read_text(encoding='utf-8'))
    return rows, taxonomy


def section_titles(taxonomy):
    titles = {}
    for d in taxonomy['domains']:
        for s in d['sections']:
            titles[f"{d['id']}:{s['id']}"] = (d, s)
    return titles


# ---- matching -------------------------------------------------------------------------------------

def stem(token):
    """Light suffix stripping so a query word also matches its other forms as a word prefix."""
    if len(token) > 3 and token.endswith('s') and not token.endswith('ss'):
        token = token[:-1]
    if len(token) > 4 and token.endswith('y'):
        return token[:-1]                       # family -> famil (family, families)
    return token


def split_cjk(run):
    """Known words first (longest match), then character pairs for what is left."""
    words = sorted((k for k in SYNONYMS if re.fullmatch(f'[{CJK}]+', k)), key=len, reverse=True)
    found, rest, i = [], [], 0
    while i < len(run):
        word = next((w for w in words if run.startswith(w, i)), None)
        if word:
            found.append(word)
            rest.append(' ')
            i += len(word)
        else:
            rest.append(run[i])
            i += 1
    pairs = []
    for piece in ''.join(rest).split():
        pairs += [piece] if len(piece) <= 2 else [piece[j:j + 2] for j in range(len(piece) - 1)]
    pairs = [p for p in pairs if p not in STOP_ZH and (len(p) > 1 or len(run) == 1)]
    return found + pairs


def query_terms(text):
    """Each term is a list of (needle, weight): the word itself first, then its synonyms (see score())."""
    terms = []
    for chunk in re.findall(f'[{CJK}]+|[a-z0-9][a-z0-9.+#]*', text.lower()):
        if re.match(f'[{CJK}]', chunk):
            for word in split_cjk(chunk):
                terms.append([(word, 1.0)] + [(s, SYNONYM_WEIGHT) for s in SYNONYMS.get(word, [])])
            continue
        token = chunk.rstrip('.')
        if token in STOP:
            continue
        alts = [(stem(token), 1.0)] + [(s, SYNONYM_WEIGHT) for s in SYNONYMS.get(stem(token), SYNONYMS.get(token, []))]
        terms.append(alts)
    return terms


def hits(needle, text):
    if re.match(f'[{CJK}]', needle):
        return needle in text
    return re.search(r'(?<![a-z0-9])' + re.escape(needle), text) is not None


def haystack(row, titles):
    d, s = titles.get(f"{row['domain']}:{row['section']}", ({'en': '', 'zh': ''}, {'en': '', 'zh': ''}))
    host = re.sub(r'^https?://(www\.)?', '', row['url']).split('/')[0]
    fields = {'name': f"{row['name']} {row.get('name_zh', '')} {row['id']}", 'tags': ' '.join(row['tags']),
              'zh': row.get('zh', ''), 'best_for': row['best_for'], 'how_to_use': row.get('how_to_use', ''),
              'host': host, 'home': f"{d['en']} {d['zh']} {s['en']} {s['zh']}"}
    return {k: v.lower() for k, v in fields.items()}


def rarity(terms, all_fields):
    """Inverse document frequency per needle: a word found in few rows says more than one found in many."""
    needles = {needle for alts in terms for needle, _ in alts}
    n = len(all_fields)
    return {needle: math.log((n + 1) / (1 + sum(any(hits(needle, text) for text in f.values()) for f in all_fields)))
            for needle in needles}


def field_weight(field, needle):
    if field == 'zh' and re.match(f'[{CJK}]', needle):
        return ZH_WEIGHT_FOR_CHINESE
    return WEIGHTS[field]


def score(terms, fields, idf):
    """Sum over query terms; each term scores its own word plus its best synonym, times the share of terms matched."""
    total, matched = 0.0, 0
    for alts in terms:
        each = [weight * idf[needle] * sum(field_weight(f, needle) for f, text in fields.items() if hits(needle, text))
                for needle, weight in alts]
        best = each[0] + max(each[1:], default=0.0)
        if best:
            matched += 1
            total += best
    return total * matched / len(terms) if terms else 0.0


def rank_key(row):
    return (TIER_RANK[row['tier']], REACH.index(row.get('agent_access', 'unknown')))


def band_of(points, best):
    """Relevance 1-4: which quarter of the best score this score falls in (0 when nothing was scored)."""
    return min(BANDS, 1 + int(BANDS * points / best)) if points and best else 0


def ranked(scored):
    """Sort (points, position, row) by relevance band, then tier, then reach, then raw score, then authored order."""
    best = max((t[0] for t in scored), default=0.0)
    return sorted(scored, key=lambda t: (-band_of(t[0], best),) + rank_key(t[2]) + (-t[0], t[1]))


# ---- filters --------------------------------------------------------------------------------------

def homes(row):
    return [f"{row['domain']}:{row['section']}"] + row.get('also', [])


def keep(row, args):
    split = lambda v: {x.strip() for x in v.replace(' ', ',').split(',') if x.strip()}
    if args.domain and not any(h.split(':')[0] == args.domain for h in homes(row)):
        return False
    if args.section and not any(h == args.section or h.split(':')[1] == args.section for h in homes(row)):
        return False
    if args.kind and row['kind'] not in split(args.kind):
        return False
    if args.tier and row['tier'] not in set(re.findall('[SAB]', args.tier.upper())):
        return False
    if args.region and row['region'] not in split(args.region):
        return False
    if args.reach and row.get('agent_access', 'unknown') not in split(args.reach):
        return False
    if args.free and row['access'] != 'free':
        return False
    return True


# ---- output ---------------------------------------------------------------------------------------

def describe(row, n=None, relevance=0):
    lead = f'{n:>2}. ' if n is not None else ''
    pad = ' ' * len(lead)
    meta = ' · '.join(([f'relevance {relevance}'] if relevance else []) +
                      [row['tier'], row['kind'], row.get('agent_access', 'unknown'), row['access']] +
                      (['login'] if row.get('login') else []) +
                      ([row['status']] if row['status'] != 'active' else []))
    lines = [f"{lead}{row['name']}  [{meta}]  {row['domain']}/{row['section']}  id: {row['id']}",
             f"{pad}{row['url']}",
             f"{pad}{row['best_for']}",
             f"{pad}中文：{row['zh']}"]
    if row.get('how_to_use'):
        lines.append(f"{pad}How: {row['how_to_use']}")
    if row.get('license'):
        lines.append(f"{pad}Licence: {row['license']}")
    if row.get('api'):
        lines.append(f"{pad}API: {row['api']['url']}   e.g. {row['api']['sample']}")
    for ep in row.get('entry_points', []):
        lines.append(f"{pad}Entry: {ep['label']}: {ep['url']}")
    for c in row.get('caveats', []):
        lines.append(f'{pad}Caveat: {c}')
    return '\n'.join(lines)


def cmd_find(rows, taxonomy, args):
    titles = section_titles(taxonomy)
    terms = query_terms(' '.join(args.keywords))
    fields = {r['id']: haystack(r, titles) for r in rows}
    idf = rarity(terms, list(fields.values()))
    pool = [r for r in rows if keep(r, args)]
    scored = [(score(terms, fields[r['id']], idf) if terms else 0.0, n, r) for n, r in enumerate(pool)]
    if terms:
        scored = [t for t in scored if t[0] > 0]
    scored = ranked(scored)
    top = scored[:args.limit]
    best = max((t[0] for t in scored), default=0.0)
    if args.json:
        print(json.dumps([dict(r, score=round(p, 2), relevance=band_of(p, best)) for p, _, r in top],
                         ensure_ascii=False, indent=1))
        return
    query = ' '.join(args.keywords) or '(no keywords)'
    order = 'relevance 4-1, then tier, then reach' if terms else 'tier, then reach'
    print(f'{len(top)} of {len(scored)} matches for "{query}" (sorted by {order})\n')
    for i, (p, _, r) in enumerate(top, 1):
        print(describe(r, i, band_of(p, best)) + '\n')
    if not scored:
        print('Nothing matched. Try fewer or broader words, or `catalog.py route "<question>"`.')


def cmd_show(rows, taxonomy, args):
    by_id = {r['id']: r for r in rows}
    row = by_id.get(args.id)
    if not row:
        close = difflib.get_close_matches(args.id, list(by_id), n=5, cutoff=0.5)
        sys.exit(f'no resource with id {args.id!r}' + (f"; did you mean: {', '.join(close)}" if close else ''))
    d, s = section_titles(taxonomy)[f"{row['domain']}:{row['section']}"]
    for key, value in row.items():
        text = value if isinstance(value, str) else json.dumps(value, ensure_ascii=False)
        print(f'{key}: {text}')
    print(f"home: {d['en']} · {d['zh']} / {s['en']} · {s['zh']} ({s['note_en']})")


def cmd_route(rows, taxonomy, args):
    titles = section_titles(taxonomy)
    terms = query_terms(args.question)
    if not terms:
        sys.exit('no keywords in the question; see `catalog.py domains`')
    fields = {r['id']: haystack(r, titles) for r in rows}
    idf = rarity(terms, list(fields.values()))
    per_home = {}
    for n, r in enumerate(rows):
        points = score(terms, fields[r['id']], idf)
        if points:
            for h in homes(r):
                per_home.setdefault(h, []).append((points, n, r))
    sections = []
    for h, members in per_home.items():
        d, s = titles[h]
        text = f"{d['en']} {d['zh']} {s['en']} {s['zh']} {s['note_en']} {s['note_zh']}".lower()
        named = sum(1 for alts in terms if any(hits(needle, text) for needle, _ in alts)) / len(terms)
        strongest = sorted((t[0] for t in members), reverse=True)[:3]
        # a section whose own title or note names the need gets up to half again: the curator filed it for that
        sections.append((sum(strongest) * (1 + 0.5 * named), h, ranked(members)))
    sections.sort(key=lambda t: -t[0])
    if not sections:
        print('No section matched. Run `catalog.py domains` to browse, or `catalog.py find` with other words.')
        return
    print(f'Best places to look for "{args.question}":\n')
    for i, (points, h, members) in enumerate(sections[:3], 1):
        d, s = titles[h]
        print(f"{i}. {h}  {s['en']} · {s['zh']}  (score {points:.0f}, {len(members)} matching)")
        print(f"   {s['note_en']}")
        for _, _, r in members[:3]:
            print(f"   - {r['name']} [{r['tier']} · {r['kind']} · {r.get('agent_access', 'unknown')}] "
                  f"{r['url']}  (id: {r['id']})")
        print()
    first = sections[0][1]
    print(f'Next: catalog.py find "{args.question}" --section {first}')


def cmd_recipes(rows, taxonomy, args):
    picked = [r for r in rows if (r.get('api') or r.get('entry_points'))
              and (not args.domain or args.domain in [h.split(':')[0] for h in homes(r)])]
    picked.sort(key=lambda r: (r['domain'], rank_key(r)))
    print(f'{len(picked)} resources with machine endpoints or agent-readable entry points\n')
    for r in picked:
        print(f"{r['name']}  [{r['tier']} · {r.get('agent_access', 'unknown')}]  {r['domain']}/{r['section']}  "
              f"id: {r['id']}")
        if r.get('api'):
            print(f"  template: {r['api']['url']}\n  sample:   {r['api']['sample']}")
        for ep in r.get('entry_points', []):
            print(f"  entry:    {ep['label']}: {ep['url']}")
        if r.get('license'):
            print(f"  licence:  {r['license']}")
        print()


def cmd_domains(rows, taxonomy, args):
    for d in taxonomy['domains']:
        members = [r for r in rows if r['domain'] == d['id']]
        s_count = sum(r['tier'] == 'S' for r in members)
        print(f"{d['id']:<8} {d['en']} · {d['zh']}  {len(members)} resources, {s_count} S")
        for s in d['sections']:
            count = sum(r['section'] == s['id'] for r in members)
            also = sum(f"{d['id']}:{s['id']}" in r.get('also', []) for r in rows)
            extra = f' (+{also} cross-listed)' if also else ''
            print(f"   {s['id']:<24} {count:>3}{extra}  {s['en']} · {s['zh']}")
        print()


def main():
    if hasattr(sys.stdout, 'reconfigure'):
        sys.stdout.reconfigure(encoding='utf-8')
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest='cmd', required=True)
    f = sub.add_parser('find', help='weighted keyword search with filters')
    f.add_argument('keywords', nargs='*')
    f.add_argument('--domain')
    f.add_argument('--section', help='section id, or domain:section')
    f.add_argument('--kind', help='comma-separated kinds, e.g. tool,library')
    f.add_argument('--tier', help='S, A, B or a list such as S,A')
    f.add_argument('--region', help='global, cn, jp, kr (comma-separated)')
    f.add_argument('--reach', help='static, js, blocked, unknown (comma-separated)')
    f.add_argument('--free', action='store_true', help='only resources whose access is free')
    f.add_argument('--limit', type=int, default=10)
    f.add_argument('--json', action='store_true')
    s = sub.add_parser('show', help='every field of one resource')
    s.add_argument('id')
    r = sub.add_parser('route', help='best sections for a question, with their top resources')
    r.add_argument('question')
    rc = sub.add_parser('recipes', help='machine endpoints and mirrors with sample requests')
    rc.add_argument('domain', nargs='?')
    sub.add_parser('domains', help='domains and sections with counts')
    args = ap.parse_args()
    rows, taxonomy = load()
    {'find': cmd_find, 'show': cmd_show, 'route': cmd_route, 'recipes': cmd_recipes,
     'domains': cmd_domains}[args.cmd](rows, taxonomy, args)


if __name__ == '__main__':
    main()
